In [4]:
import numpy as np

print(np.__version__)
# print(dir(np))

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

1.21.3
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# NumPy Creating Arrays
import numpy as np

# Dimensions in Arrays
arr0 = np.array(24)
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr0.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

# Higher Dimensional Arrays
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

In [ ]:
# NumPy Array Indexing
import numpy as np

# Access Array Elements
arr01 = np.array([1, 2, 3, 4])
print(arr01[2] + arr01[3])

# Access 2-D Arrays
arr02 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr02[0, 1])
print('5th element on 2nd row: ', arr02[1, 4])

# Access 3-D Arrays
arr03 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr03[0, 1, 2])

# Negative Indexing
arr04 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr04[1, -1])

In [ ]:
# NumPy Array Slicing
import numpy as np

# We pass slice instead of index like this: [start:end]
# We can also define the step, like this: [start:end:step]
# Note: The result includes the start index, but excludes the end index

arr01 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr01[1:5])
print(arr01[2:])
print(arr01[:4])

# Negative Slicing
print(arr01[-3:-1])

# STEP
print(arr[1:5:2])
print(arr[::2])

# Slicing 2-D Arrays
arr02 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr02[1, 1:4])
print(arr02[0:2, 2])
print(arr02[0:2, 1:4])

In [3]:
# NumPy Data Types
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [1]:
# NumPy Array Copy vs View
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [2]:
# NumPy Array Shape
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr)
print('shape of array :', arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
shape of array : (2, 4)


In [ ]:
# NumPy Array Reshaping
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr01 = arr.reshape(2, 3, -1)
newarr02 = arr.reshape(-1)

print(newarr01)
print(newarr01.base)
print(newarr02)


In [1]:
# NumPy Array Iterating
import numpy

arr01 = numpy.array([[1, 2, 3], [4, 5, 6]])

for x in arr01:
    for y in x:
        print(y)

# Iterating Arrays Using nditer()
arr02 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in numpy.nditer(arr02):
    print(x)


ModuleNotFoundError: No module named 'numpy'